# font configuration
font_size 12.0

# window configuration
confirm_os_window_close 0
window_padding_width 4
background_opacity 1.0
background_blur 32
hide_window_decorations yes

# cursor configuration
cursor_shape block
cursor_blink_interval 0

# scrollback
scrollback_lines 3000

# terminal features
strip_trailing_spaces smart

map ctrl+s>c new_tab_with_cwd
map ctrl+s>w close_tab
map ctrl+s>n next_tab
map ctrl+s>p previous_tab
map ctrl+s>r set_tab_title
map ctrl+s>0 goto_tab 1
map ctrl+s>1 goto_tab 2
map ctrl+s>2 goto_tab 3
map ctrl+s>3 goto_tab 4
map ctrl+s>4 goto_tab 5
map ctrl+s>5 goto_tab 6
map ctrl+s>6 goto_tab 7
map ctrl+s>7 goto_tab 8
map ctrl+s>8 goto_tab 9
map ctrl+s>[ show_scrollback
map ctrl+plus change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0 change_font_size all 0

# tab configuration
tab_bar_edge bottom
tab_title_template " {index-1}:{tab.active_exe[:12]} "

# dank color generation
include dank-theme.conf
