include oxocarbon.conf
confirm_os_window_close 0
background #161616
font_family      family="Adwaita Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
cursor_blink_interval 0

# tab bar
tab_bar_edge bottom
tab_bar_style separator
tab_separator " "
tab_title_template " {index-1}:{tab.active_exe[:12]} "
active_tab_title_template " {index-1}:{tab.active_exe[:12]}{fmt.fg._00afff}*{fmt.fg.default} "
tab_bar_background #161616
inactive_tab_background #161616
inactive_tab_foreground #9e9e9e
active_tab_background #161616
active_tab_foreground #ffffff
active_tab_font_style normal

map ctrl+s>c new_tab_with_cwd
map ctrl+s>d close_tab
map ctrl+s>n next_tab
map ctrl+s>p previous_tab
map ctrl+s>r set_tab_title
map ctrl+s>0 goto_tab 1
map ctrl+s>1 goto_tab 2
map ctrl+s>2 goto_tab 3
map ctrl+s>3 goto_tab 4
map ctrl+s>4 goto_tab 5
map ctrl+s>5 goto_tab 6
map ctrl+s>6 goto_tab 7
map ctrl+s>7 goto_tab 8
map ctrl+s>8 goto_tab 9
map ctrl+s>[ show_scrollback
