source=./rules.conf

# MONITOR:
#
monitorrule=name:HDMI-A-1,width:1920,height:1080,refresh:74.973000,x:0,y:0

# INPUT DEVICES:
#
# keyboard:
xkb_rules_layout = us,es
xkb_rules_options = caps:escape
bind=alt,shift_l,switch_keyboard_layout
numlockon = 0

# MISCELLANEOUS
#
sloppyfocus = 0

# KEYBINDS:
#
#(system)
bind=SUPER+SHIFT,c,reload_config 
bind=SUPER+SHIFT,e,spawn_shell,loginctl terminate-user ""
bind=SUPER,q,killclient
#(menu and terminal)
bind=SUPER,Return,spawn_shell,~/.config/twm-scripts/uwsm_wrap.sh kitty
bind=SUPER,d,spawn_shell,~/.config/twm-scripts/menu.sh
#(screenshots / colorpicker)
bind=SUPER+SHIFT,p,spawn_shell,hyprpicker | wl-copy
bind=SUPER+SHIFT,s,spawn_shell,~/.config/twm-scripts/area_screenshot.sh
bind=NONE,Print,spawn_shell,~/.config/twm-scripts/screenshot.sh
#(switch window focus)
bind=SUPER,h,focusdir,left
bind=SUPER,l,focusdir,right
bind=SUPER,k,focusdir,up
bind=SUPER,j,focusdir,down
#(swap window)
bind=SUPER+SHIFT,k,exchange_client,up
bind=SUPER+SHIFT,j,exchange_client,down
bind=SUPER+SHIFT,h,exchange_client,left
bind=SUPER+SHIFT,l,exchange_client,right
#(switch window status)
bind=SUPER,o,toggleoverview,
bind=SUPER+SHIFT,space,togglefloating,
bind=SUPER,m,togglemaximizescreen,
bind=SUPER,f,togglefullscreen,
#(tag switch)
bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0
#(move client to the tag and focus it)
bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0
bind=SUPER+SHIFT,6,tag,6,0
bind=SUPER+SHIFT,7,tag,7,0
bind=SUPER+SHIFT,8,tag,8,0
bind=SUPER+SHIFT,9,tag,9,0
#(move and resize windows with left click/right click)
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize 

# APPEARANCE:
#
# dimensions:
borderpx = 1
gappoh = 0
gappov = 0
gappiv = 0
gappih = 0
# colors:
#(active window border)
focuscolor=0x6C757Dff
maximizescreencolor=0x6C757Dff

# WINDOW MANAGEMENT:
#
enable_hotarea = 0

#(options: tile,scroller,grid,deck,monocle,center_tile,vertical_tile,vertical_scroller)
tagrule=id:1,layout_name:scroller
tagrule=id:2,layout_name:scroller
tagrule=id:3,layout_name:scroller
tagrule=id:4,layout_name:scroller
tagrule=id:5,layout_name:scroller
tagrule=id:6,layout_name:scroller
tagrule=id:7,layout_name:scroller
tagrule=id:8,layout_name:scroller
tagrule=id:9,layout_name:scroller
