windowrule=isfloating:1,width:100,height:200,appid:org.gnome.Calculator
windowrule=isfloating:1,width:1024,height:576,appid:org.gnome.Nautilus
windowrule=tags:4,appid:tidal-hifi
windowrule=tags:4,appid:discord
