[font]
normal = { family = "IosevkaTerm NFM" }
size = 12
[window]
decorations = "None"
startup_mode = "Maximized"
padding = { x = 4, y = 4 }
[colors]
footer_bar = { background = "#262626", foreground = "#ffffff"}
[colors.primary]
background = "#161616"
foreground = "#ffffff"

[colors.search]
matches = { foreground =  "CellBackground", background = "#ee5396" }
[colors.normal]
black = "#262626"
magenta = "#ff7eb6"
green = "#42be65"
yellow = "#ffe97b"
blue = "#33b1ff"
red = "#ee5396"
cyan = "#3ddbd9"
white = "#dde1e6"

[colors.bright]
black = "#393939"
magenta = "#ff7eb6"
green = "#42be65"
yellow = "#ffe97b"
blue = "#33b1ff"
red = "#ee5396"
cyan = "#3ddbd9"
white = "#ffffff"
